### PR TITLE
Social

### PR DESCRIPTION
**Pull request by pgrenaud**
Added social links in footer. Also, fixed invalid `padding-top` value on `.body` element.

### CODE REVIEW

**Comment by pgrenaud** [comment]
Fixes #131.

**Comment by S0yKaf** [comment]
screenshot please

**Comment by pgrenaud** [comment]
Screenshot

**Comment by S0yKaf** [comment]
umm :-1: facebook

**Comment by jdupl** [comment]
:-1: facebook

**Comment by sm-Fifteen** [comment]
Muh privacy! :-1: 
http://panzi.github.io/SocialSharePrivacy/

**Comment by jdupl** [comment]
:+1: pour le widgets qui se ferment

**Pull request closed without merging**
